"""Add plan and country to tenants

Revision ID: 8f801c2979f8
Revises: f8a5a7d15604
Create Date: 2025-07-16 15:25:50.844873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f801c2979f8'
down_revision: Union[str, None] = 'f8a5a7d15604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Auto-generated schema changes
    op.alter_column('document_interactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_interactions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tenants', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(), nullable=True))

    # Populate default values for existing tenants
    op.execute("UPDATE tenants SET plan = 'basic' WHERE plan IS NULL")
    op.execute("UPDATE tenants SET country = 'Kenya' WHERE country IS NULL")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'plan')
    op.alter_column('document_interactions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_interactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
