"""Add status column to documents

Revision ID: cf46302b3400
Revises: 49f80ced7380
Create Date: 2025-07-14 11:48:14.651533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf46302b3400'
down_revision: Union[str, None] = '49f80ced7380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the status column
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))

    # Update all existing rows to 'processed'
    op.execute("UPDATE documents SET status = 'processed'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
